### ISSUE TITLE
argument order in location and move different

### ISSUE THREAD

**Issue by MaxNoe** [erikrose/blessings#113] opened 2015-08-05 20:49 UTC
Why is the order of the arguments different in `move` and  `location`?

This is really unintuitive and makes the code really difficult to read. Especially 
since move does not even have keyword arguments.

**Comment by erikrose** [comment] 2015-08-08 14:50
Legacy. I designed location() and later discovered move, which is a built-in capability and so can't have its order changed. We'll correct it in 2.0.

**Comment by jquast** [comment] 2015-10-09 22:49
Closing as duplicate of #58

**Closed by jquast** 2015-10-09 22:49 UTC
Labels: duplicate
